# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6260b29c63d81c9cd4d10f4989a9cf61c235e3f9c12643134a56c3c33b7fa13b1e1ec6b3302f073a8571472882d647b1980d0789b96fd31e497eb5c5710d348

test:
  secret_key_base: e16b3624293f268ee5767a5b19a6b104398b4665a0d014fffdba2b80c3d1f35c11ef9524c6ba3d5a2fde148445b9544645e3475aa7abe4fcbaf3afd0de24b415

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
